language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

install:
    - composer self-update
    - composer update --no-interaction --prefer-source
    - |
        COVERAGE_PHP_VERSION='5.6'

before_script:
    - |
        if [ $TRAVIS_PHP_VERSION = $COVERAGE_PHP_VERSION ]; then
            PHPUNIT_FLAGS='--coverage-clover=coverage.clover'
        fi

script:
    - vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
    - |
        if [ $TRAVIS_PHP_VERSION = $COVERAGE_PHP_VERSION ]; then
            wget https://scrutinizer-ci.com/ocular.phar
            php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        fi
